<?php

namespace Shakyamouni\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SubscriptionEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionEventRepository extends EntityRepository
{
}
