<?php

namespace Shakyamouni\SiteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SliderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SliderRepository extends EntityRepository
{
    public function getSliders($max = null)
    {
        $qb = $this->createQueryBuilder('s')
                ->OrderBy('s.position', 'ASC');

        if (false === is_null($max))
            $qb->setMaxResults($max);

        return $qb->getQuery()
                        ->getResult();
    }

}