<?php

namespace Shakyamouni\SiteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SlideShowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlideShowRepository extends EntityRepository
{
}
