imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: common_parameters.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [FMElfinderBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

services:
    twig.extension.text:
     class: Twig_Extensions_Extension_Text
     tags:
         - { name: twig.extension }
         
    twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
           - { name: twig.extension }
        
stof_doctrine_extensions:
    default_locale: fr_FR
    orm:
        default:
            timestampable: true
            sluggable: true
            
avalanche_imagine:
    web_root:     %kernel.root_dir%/../web
    cache_prefix: imagine
    driver:       gd
    filters:
        thumbnail_87x113:
            type:    thumbnail
            options: { size: [87, 113], mode: outbound, quality: 100 }
        thumbnail_135x180:
            type:    thumbnail
            options: { size: [135, 180], mode: outbound, quality: 100 }
        thumbnail_140x200:
            type:    thumbnail
            options: { size: [140, 200], mode: outbound, quality: 100 }
        thumbnail_140x90:
            type:    thumbnail
            options: { size: [140, 90], mode: outbound, quality: 100 }
        thumbnail_150x103:
            type:    thumbnail
            options: { size: [150, 103], mode: outbound, quality: 100 }
        thumbnail_150x150:
            type:    thumbnail
            options: { size: [150, 150], mode: outbound, quality: 100 }
        thumbnail_160x120:
            type:    thumbnail
            options: { size: [160, 120], mode: outbound, quality: 100 }
        thumbnail_175x227:
            type:    thumbnail
            options: { size: [175, 227], mode: outbound, quality: 100 }
        thumbnail_200x200:
            type:    thumbnail
            options: { size: [200, 200], mode: outbound, quality: 100 }
        thumbnail_200x133:
            type:    thumbnail
            options: { size: [200, 133], mode: outbound, quality: 100 }
        thumbnail_220x200:
            type:    thumbnail
            options: { size: [220, 200], mode: outbound, quality: 100 }
        thumbnail_220x150:
            type:    thumbnail
            options: { size: [220, 150], mode: outbound, quality: 100 }
        thumbnail_230x300:
            type:    thumbnail
            options: { size: [230, 300], mode: outbound, quality: 100 }
        thumbnail_240x160:
            type:    thumbnail
            options: { size: [240, 160], mode: outbound, quality: 100 }
        thumbnail_270x180:
            type:    thumbnail
            options: { size: [270, 180], mode: outbound, quality: 100 }
        thumbnail_200x300:
            type:    thumbnail
            options: { size: [200, 300], mode: outbound, quality: 100 }
        thumbnail_300x200:
            type:    thumbnail
            options: { size: [300, 200], mode: outbound, quality: 100 }
        thumbnail_300x225:
            type:    thumbnail
            options: { size: [300, 225], mode: outbound, quality: 100 }       
        thumbnail_480x180:
            type:    thumbnail
            options: { size: [480, 180], mode: outbound, quality: 100 }    
        thumbnail_285x63:
            type:    thumbnail
            options: { size: [285, 63], mode: outbound, quality: 100 }
        thumbnail_960x360:
            type:    thumbnail
            options: { size: [960, 360], mode: outbound, quality: 100 }
                

stfalcon_tinymce:
        include_jquery: false
        tinymce_jquery: false
        selector: ".tinymce"
        language: %locale%
        # Custom buttons
        tinymce_buttons:
            stfalcon: # Id of the first button
                title: "Stfalcon"
                image: "http://stfalcon.com/favicon.ico"
        theme: 
            # Simple theme: same as default theme
            simple:
                theme: "modern"
                plugins:
                     - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
                     - "searchreplace wordcount visualblocks visualchars code fullscreen"
                     - "insertdatetime media nonbreaking save table contextmenu directionality"
                     - "emoticons template paste textcolor"
                toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
                toolbar2: "print preview media | forecolor backcolor emoticons | example"
                image_advtab: true
                file_browser_callback : elFinderBrowser
            advanced:
                theme: "modern"
                plugins:
                     - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
                     - "searchreplace wordcount visualblocks visualchars code fullscreen"
                     - "insertdatetime media nonbreaking save table contextmenu directionality"
                     - "emoticons template paste textcolor"
                toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
                toolbar2: "print preview media | forecolor backcolor emoticons | example"
                image_advtab: true
                file_browser_callback : elFinderBrowser
            # BBCode tag compatible theme (see http://www.bbcode.org/reference.php)
            bbcode:
                plugins: ["bbcode, code, link, preview"]
                menubar: false
                toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"

fm_elfinder:
    instances:
        default:
            locale: %locale% # defaults to current request locale
            editor: tinymce4 # other choices are tinymce or simple
            tinymce_popup_path: "asset[bundles/stfalcontinymce/vendor/tiny_mce/tiny_mce_popup.js]"
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            compression: false # enable if you configured the uglifycss and uglifyjs2 assetic filters and want compression
            connector:
                debug: false # defaults to false
                roots:       # at least one root must be defined
                    uploads:
                        showhidden: false # defaults to false
                        driver: LocalFileSystem
                        path: uploads
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg', 'image/gif', 'image/tiff', 'application/pdf', 'application/msword']
                        upload_deny: ['all']
                        upload_max_size: 4M

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Shakyamouni\UserBundle\Entity\User
    

lexik_mailer:
    admin_email: %your_admin_email%
    base_layout: "::layoutMail.html.twig"  # personnal value is "ProjectBundle:path:template.html.twig"
    templating_extensions:
        - 'twig.extension.trans' # load the translation extension
    classes:
        email_entity:      "Lexik\Bundle\MailerBundle\Entity\Email"               # the email entity to use to represent an email template
        annotation_driver: "Lexik\Bundle\MailerBundle\Mapping\Driver\Annotation"  # annotation driver used to get the user's name and email
        message_factory:   "Lexik\Bundle\MailerBundle\Message\MessageFactory"     # message factory service class
        message_renderer:  "Lexik\Bundle\MailerBundle\Message\MessageRenderer"    # message renderer service class

lexik_translation:
    fallback_locale: fr      # (required) default locale to use
    managed_locales: [fr]    # (required) locales that the bundle have to manage
    base_layout:     "LexikTranslationBundle::layout.html.twig" # layout used with the translation edition template
    use_yml_tree:    true    # if "true" we will print a nice tree in the yml source files. It is a little slower.
    grid_input_type: text     # define field type used in the grid (text|textarea)
    resources_registration:
        type:                 all     # resources type to register: "all", "files" or "database"
        managed_locales_only: true    # will only load resources for managed locales