shakyamouni_admin:
    resource: "@ShakyamouniAdminBundle/Controller/"
    type:     annotation
    prefix:   /cmk-bo-path

shakyamouni_menu:
    resource: "@ShakyamouniMenuBundle/Controller/"
    type:     annotation
    prefix:   /

shakyamouni_site:
    resource: "@ShakyamouniSiteBundle/Controller/"
    type:     annotation
    prefix:   /

shakyamouni_user:
    resource: "@ShakyamouniUserBundle/Controller/"
    type:     annotation
    prefix:   /
    
_imagine:
    resource: .
    type:     imagine
    
elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"
     prefix:   /cmk-bo-path
     
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /cmk-bo-path/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: cmk-bo-path/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: cmk-bo-path/profile

LexikMailerBundle:
    resource: "@LexikMailerBundle/Resources/config/routing.xml"
    prefix:   /cmk-bo-path
    
lexik_translation_edition:
    resource: "@LexikTranslationBundle/Resources/config/routing.yml"
    prefix:   /cmk-bo-path

#login:
#    pattern:   /login
#    defaults:  { _controller: ShakyamouniUserBundle:Security:login }
 
#login_check:
#    pattern:   /login_check
 
#logout:
#    pattern:   /logout

# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
