<?php

namespace Shakyamouni\MenuBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository {

    public function getCategoryOrSubCategoryWithArticles()
    {
        $qb = $this->createQueryBuilder('c')
                ->leftJoin('c.subCategories', 'sc')
                ->addSelect('sc')
                ->OrderBy('c.position', 'ASC');

        return $qb->getQuery()
                        ->getResult();
    }
    
    public function getCategoryOrSubCategoryExceptCalendarContactEvent()
    {
        $qb = $this->createQueryBuilder('c')
                ->leftJoin('c.subCategories', 'sc')
                ->addSelect('sc')
                ->andWhere('c.eventCat = :eventCat')
                ->setParameter('eventCat', false)
                ->andWhere('c.contactCat = :contactCat')
                ->setParameter('contactCat', false)
                ->andWhere('c.calendarCat = :calendarCat')
                ->setParameter('calendarCat', false)
                ->OrderBy('c.position', 'ASC')
                ->addOrderBy('sc.position', 'ASC');

        return $qb->getQuery()
                        ->getResult();
    }
    
    public function getEventCategory()
    {
        $qb = $this->createQueryBuilder('c')
                ->andWhere('c.eventCat = :eventCat')
                ->setParameter('eventCat', true);

        return $qb->getQuery()
                        ->getOneOrNullResult();
    }
    
    public function getCalendarCategory()
    {
        $qb = $this->createQueryBuilder('c')
                ->andWhere('c.calendarCat = :calendarCat')
                ->setParameter('calendarCat', true);

        return $qb->getQuery()
                        ->getOneOrNullResult();
    }
    
    public function getContactCategory()
    {
        $qb = $this->createQueryBuilder('c')
                ->andWhere('c.contactCat = :contactCat')
                ->setParameter('contactCat', true);

        return $qb->getQuery()
                        ->getOneOrNullResult();
    }
}
