<?php

namespace Shakyamouni\MenuBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SubCategoryEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubCategoryEventRepository extends EntityRepository {

    public function getFirstSubCategoryEvent($position)
    {
        $qb = $this->createQueryBuilder('sc')
                ->where('sc.position = :position')
                ->setParameter('position', $position);

        return $qb->getQuery()
                        ->getOneOrNullResult();
    }
    
    public function getVisibleFirstSubCategoryEvent()
    {
        $qb = $this->createQueryBuilder('sc')
                ->where('sc.isVisible = :is_visible')
                ->setParameter('is_visible', true)
                ->setMaxResults(1)
                ->OrderBy('sc.position', 'ASC');

        return $qb->getQuery()
                        ->getResult();
    }

    public function getSubCategoriesEventWithEvents()
    {
        $qb = $this->createQueryBuilder('sc')
                ->leftJoin('sc.events', 'e')
                ->addSelect('e')
                ->where('e is not null')
                ->OrderBy('sc.position', 'ASC');

        return $qb->getQuery()
                        ->getResult();
    }
    
    public function getSubCategoriesEventbyTitreASC()
    {
        $qb = $this->createQueryBuilder('sc')
                ->orderBy('sc.title', 'ASC');

        return $qb;
    }
    
    public function getSubCategoriesEventbyPositionASC()
    {
        $qb = $this->createQueryBuilder('sc')
                ->orderBy('sc.position', 'ASC');

        return $qb->getQuery()
                        ->getResult();
    }

}
