<?php

namespace Shakyamouni\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CalendarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendarRepository extends EntityRepository
{
    public function getLastActiveCalendarUpdatedQuery()
    {
        $qb = $this->createQueryBuilder('c')
             //   ->where('c.isActive = :isActive')
             //   ->setParameter('isActive', true)
             //   ->setMaxResults(1)
                ->orderBy('c.id', 'DESC');

        return $qb;
    }
    
    public function getActiveCalendarUpdatedQuery()
    {
        $qb = $this->createQueryBuilder('c')
                ->where('c.isActive = :isActive')
                ->setParameter('isActive', true)
                ->setMaxResults(1)
                ->orderBy('c.id', 'DESC');

        return $qb;
    }
    
    
    public function getLatestActiveCalendarUpdated()
    {
        $qb = $this->getLastActiveCalendarUpdatedQuery();

        return $qb->getQuery()
//                        ->getOneOrNullResult();
                        ->getResult();
    }
    
    public function getLastActiveCalendarUpdated()
    {
        $qb = $this->getActiveCalendarUpdatedQuery();

        return $qb->getQuery()
                        ->getOneOrNullResult();
    }
}
