<?php

namespace Shakyamouni\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NewsletterArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterArticleRepository extends EntityRepository
{
    public function getArticlesByPosition($newsletter_id)
    {
        $qb = $this->createQueryBuilder('n')
                ->where('n.newsletter = :id')
                ->setParameter('id', $newsletter_id)
                ->orderBy('n.position', 'ASC');

        return $qb->getQuery()
                        ->getResult();;
    }
}
