<?php

namespace Shakyamouni\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * SubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionRepository extends EntityRepository
{

    public function getPricesBySubscription($id)
    {
        $qb = $this->createQueryBuilder('s')
                ->select('s.maxPrice, s.mediumPrice, s.lowPrice, s.percentage')
                ->where('s.id = :id')
                ->setParameter('id', $id);

        $tabResults = $qb->getQuery()
                ->getResult();

        $tabPrices = array();
        $arrhesAmount = 0;

        foreach ($tabResults[0] as $key => $val) {
            $arrhesAmount = ($tabResults[0]['percentage'] * $val)/100;
            if (!is_null($val) && in_array($key, array('maxPrice', 'mediumPrice', 'lowPrice'))) {
                $sentence = self::getPriceLabel($key) . ': ' . (float)$val . ' €';
                if ($tabResults[0]['percentage'] != 100) {
                    $sentence .= ', soit '. $arrhesAmount .'€ d\'arrhes';
                }
                $tabPrices[$key] = $sentence;
            }
        }

        return $tabPrices;
    }
    
    public static function getPriceLabel($key){
        $tab = array(
            'maxPrice' => "Tarif",
            'mediumPrice' => "Tarif réduit",
            'lowPrice' => "Tarif membre",
        );
        
        return $tab[$key];
    }
}
